services:
  load:
    image: ${REPO}/rs-load:${TAG}
    build:
      context: load-gen
    environment:
      HOST: http://web:8080
      NUM_CLIENTS: 15
      RUN_TIME: 30m
      ERROR: 1
    networks:
      - robot-shop
    depends_on:
      - web
    logging: &logging
      driver: "json-file"
      options:
        max-size: "25m"
        max-file: "2"
