services:
  load:
    image: ${REPO}/rs-load:${TAG}
    build:
      context: load-gen
    environment:
      HOST: http://201.54.12.94:8080/
      NUM_CLIENTS: 15
      RUN_TIME: 30m
      ERROR: 1
    logging: &logging
      driver: "json-file"
      options:
        max-size: "25m"
        max-file: "2"
